# This is a basic workflow to help you get started with Actions

name: retrieve

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_dispatch:



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '>=14'
          check-latest: true
        
      # Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          DSTDIR=./force-app

          if [ ! -d $DSTDIR ]; then
            mkdir $DSTDIR
          fi

          npm install sfdx-cli
          node_modules/sfdx-cli/bin/run --version
          node_modules/sfdx-cli/bin/run plugins --core
      
      - name: 'SFDX_AUTH_URLをSFDX_AUTH_URL_FILEファイルに保存'
        shell: bash
        run : 'echo ${{  secrets.SFDX_AUTH_URL }} > SFDX_AUTH_URL_FILE'

      - name: 'Authenticate'
        run: node_modules/sfdx-cli/bin/run force:auth:sfdxurl:store -f SFDX_AUTH_URL_FILE -s -a MYDEV

      - name: 'retrieve devhub'
        run: node_modules/sfdx-cli/bin/run force:source:retrieve --manifest ./manifest/package.xml

      - name: git setting
        run: |
          git config --local user.email ${{ secrets.EMAIL }}
          git config --local user.name ${{ secrets.UNAME }}

      - name: '  fetch'
        run: |
           git fetch
      - name: '  add'
        run: |
           git add ./force-app
      - name: '  commit'
        run: |
           git commit -m "retrieve"
      - name: '  push'
        run: |
           git push origin HEAD
